language: python

python:
  - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls

script: coverage run --source pathway_assessor/tests/ test_pathway_assessor.py

after_success:
    coveralls
